#pragma once

#include <vector>
#include <optional>
#include <string>
#include <chrono>

namespace solax
{

// QPGSn response structure - Parallel Information inquiry
struct UnitTelemetry {
    int32_t parallelNum{0};                      // A: Parallel machine number (0: not exist, 1: exist)
    std::string serialNumber;                    // B: 14-digit serial number
    char workMode{'P'};                          // C: Work mode (P/S/L/B/F/D)
    int32_t faultCode{0};                        // D: Fault code (00-86)
    float gridVoltage_V{0.0f};                   // E: Grid voltage (V)
    float gridFrequency_Hz{0.0f};                // F: Grid frequency (Hz)
    float acOutputVoltage_V{0.0f};               // G: AC output voltage (V)
    float acOutputFrequency_Hz{0.0f};            // H: AC output frequency (Hz)
    int32_t acOutputApparentPower_VA{0};         // I: AC output apparent power (VA)
    int32_t acOutputActivePower_W{0};            // J: AC output active power (W)
    int32_t loadPercent{0};                      // K: Load percentage (%)
    float batteryVoltage_V{0.0f};                // L: Battery voltage (V)
    int32_t batteryChargingCurrent_A{0};         // M: Battery charging current (A)
    int32_t batteryCapacity_pct{0};              // N: Battery capacity (%)
    float pv1InputVoltage_V{0.0f};               // O: PV1 input voltage (V)
    int32_t totalChargingCurrent_A{0};           // P: Total charging current (A)
    int32_t totalAcOutputApparentPower_VA{0};    // Q: Total AC output apparent power (VA)
    int32_t totalOutputActivePower_W{0};         // R: Total output active power (W)
    int32_t totalAcOutputPercent{0};             // S: Total AC output percentage (%)
    std::string inverterStatus;                  // U: Inverter status bits (b7-b0)
    int32_t outputMode{0};                       // T: Output mode (0-7)
    int32_t chargerSourcePriority{0};            // U: Charger source priority (0-3)
    int32_t maxChargerCurrent_A{0};              // V: Max charger current (A)
    int32_t maxChargerRange_A{0};                // W: Max charger range (A)
    int32_t maxAcChargerCurrent_A{0};            // Z: Max AC charger current (A)
    int32_t pv1InputCurrent_A{0};                // a: PV1 input current (A)
    int32_t batteryDischargeCurrent_A{0};        // b: Battery discharge current (A)
    float pv2InputVoltage_V{0.0f};               // c: PV2 input voltage (V)
    int32_t pv2InputCurrent_A{0};                // d: PV2 input current (A)
};

struct AggregatedTelemetry {
    float solarPower_W{};                        // Total power generated by photovoltaik
    float acPower_W{};                           // Total power put into the AC
    float batteryPower_W{};                      // Total power put into the battery (can be negative while discharing the battery)
};



UnitTelemetry parseRawTelemetry(const std::string& rawTelemetry);

AggregatedTelemetry aggregateTelemetry(const std::vector<UnitTelemetry>& unitTelemetry);

}